{
 "title": "Observability: Website Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "prod,stage" },
   { "name": "country", "query": "US,NL,DE,GB,IN,ES,SE,IE,ZA" },
   { "name": "device", "query": "desktop,mobile" },
   { "name": "percentile", "query": "10,50,75,90,95,99" }
  ]
 },
 "panels": [
  { "title": "Aggregated", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CHR by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields event_details.env as env1\n|filter event_type='cdn_metrics' and (event_details.metricType='TTFB' or event_details.metricType='RESOURCE') and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}] \n|stats COALESCE(count(event_details.sthcdncachemiss),0) as cachemiss,COALESCE(count(event_details.sthcdncachehit),0) as cachehit by bin(5m) as event_timestamp,env1\n|display event_timestamp,env1,cachehit/(cachehit+cachemiss)",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env1"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type=\"cdn_metrics\" and (event_details.initiatorType=\"navigation\" or event_details.initiatorType=\"script\" or event_details.initiatorType=\"link\" ) and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats avg(event_details.compressRate) as compression by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Page Views - ${country}",
   "type": "stat",
   "gridPos": { "h": 10, "w": 13, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "fields concat(event_details.env,'-',metadata.countryCode) as env\n|filter event_type='cdn_metrics' and event_details.initiatorType='navigation' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats count() as pageViews by bin(5m) as event_timestamp,env\n|sort pageViews desc",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env"
     ]
    },
    {
     "expression": "fields concat(event_details.env,'-Global') as env\n|filter event_type='cdn_metrics' and event_details.initiatorType='navigation' and event_details.env in [${environment:singlequote}]\n|stats count() as pageViews by bin(5m) as event_timestamp,env\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env"
     ]
    }
   ]
  },
  {
   "title": "Total bytes by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "filter event_type=\"cdn_metrics\" and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Page Views by Devices by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields concat(event_details.env,'-',metadata.deviceType) as env\n|filter event_type='cdn_metrics' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats count() as deviceCount by bin(5m) as event_timestamp,env,metadata.countryCode\n|display event_timestamp,env,deviceCount",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env",
      "metadata.countryCode"
     ]
    }
   ]
  },
  {
   "title": "CloudFront to Origin FBL by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.sthcdndownstreamfblduration,${percentile}) as originFBL by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,originFBL",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "CHR by Behavior by environment: ${country}",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' \n|filter event_details.metricType='RESOURCE' or event_details.metricType='TTFB' \n|filter event_details.env in [${environment:singlequote}]  and metadata.countryCode in [${country:singlequote}]\n|stats count(event_details.sthcdncachehit) as cachehit,count(event_details.sthcdncachemiss) as cachemiss,cachehit/(cachemiss+cachehit) as chr by event_details.sthbehavior as behavior,event_details.env\n|display behavior,event_details.env,chr\n|sort behavior",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "behavior",
      "event_details.env"
     ]
    }
   ]
  },
  {
   "title": "Average Object Size by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type=\"cdn_metrics\" and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize, count() as totalRequests by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize/totalRequests ",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "TLS connect time(p${percentile}): ${country}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields event_details.env as env\n|filter event_details.metricType='TTFB' and env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.connectionTime,${percentile}) as connecttime by env,bin(5m) as event_timestamp\n|display event_timestamp,env,connecttime",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "#Requests with non 200OK",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "connectionArgs": { "catalog": "__default", "database": "__default", "region": "__default" },
     "rawSQL": "select sc_status,count(*) from rtlogs2 where dt between '${__from:date:YYYY-MM-DD-HH}' and '${__to:date:YYYY-MM-DD-HH}' and sc_status!='200' and c_country in (${country:singlequote}) group by sc_status;",
     "table": "rtlogs2"
    }
   ]
  },
  {
   "title": "Page Views by Edge Location: ${country}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 19 },
   "targets": [
    {
     "expression": "fields metadata.countryCode as countryCode\n|filter event_type='cdn_metrics' and event_details.initiatorType='navigation' and event_details.env in [${environment:singlequote}] \n|filter countryCode in [${country:singlequote}]\n|stats count() as pageViews by bin(5m) as event_timestmap,event_details.sthcdnpop",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestmap",
      "event_details.sthcdnpop"
     ]
    }
   ]
  },
  {
   "title": "Busiest Edge Locations (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and metadata.countryCode in [${country:singlequote}] and event_details.env in [${environment:singlequote}]\n|stats sum(event_details.transferSize) as totalBytes by event_details.sthcdnpop as PoP\n|display PoP,totalBytes\n|sort totalBytes desc\n|limit 10",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "PoP" ]
    }
   ]
  },
  { "title": "Pages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CHR by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields event_details.env as env1\n|filter event_type='cdn_metrics' and (event_details.initiatorType='navigation') and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}] \n|stats COALESCE(count(event_details.sthcdncachemiss),0) as cachemiss,COALESCE(count(event_details.sthcdncachehit),0) as cachehit by bin(5m) as event_timestamp,env1\n|display event_timestamp,env1,cachehit/(cachehit+cachemiss)",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env1"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type=\"cdn_metrics\" and (event_details.initiatorType=\"navigation\") and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats avg(event_details.compressRate) as compression by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "FCP & LCP by environment (p${percentile}): ${country}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "filter event_details.metricType='FCP'and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.value,${percentile}) as fcp by event_details.metricType,event_details.env,bin(1m) as event_timestamp\n|display event_timestamp,event_details.env,fcp",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.metricType",
      "event_details.env",
      "event_timestamp"
     ]
    },
    {
     "expression": "filter event_details.metricType='LCP' and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.value,${percentile}) as lcp by event_details.metricType,event_details.env,bin(1m) as event_timestamp\n|display event_timestamp,event_details.env,lcp",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.metricType",
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Average Object Size by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.initiatorType='navigation' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize, count() as totalRequests by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize/totalRequests ",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "TTFB (p${percentile}): ${country}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields event_details.env as env\n|filter event_details.metricType='TTFB' and env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.value,${percentile}) as ttfb by env,bin(5m) as event_timestamp\n|display event_timestamp,env,ttfb",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "TLS connect time (p${percentile}): ${country}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields event_details.env as env\n|filter event_details.metricType='TTFB' and env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.connectionTime,${percentile}) as connecttime by env,bin(5m) as event_timestamp\n|display event_timestamp,env,connecttime",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "env",
      "event_timestamp"
     ]
    }
   ]
  },
  { "title": "Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CHR by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields event_details.env as env1\n|filter event_type='cdn_metrics' and (event_details.initiatorType='img') and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}] \n|stats COALESCE(count(event_details.sthcdncachemiss),0) as cachemiss,COALESCE(count(event_details.sthcdncachehit),0) as cachehit by bin(5m) as event_timestamp,env1\n|display event_timestamp,env1,cachehit/(cachehit+cachemiss)",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env1"
     ]
    }
   ]
  },
  {
   "title": "TTFB (p${percentile}): ${country}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 5, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields event_details.env as env\n|filter event_details.initiatorType='img' and env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.requestTime,${percentile}) as ttfb by env,bin(5m) as event_timestamp\n|display event_timestamp,env,ttfb",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Total bytes served by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.initiatorType='img' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Average Object Size by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.initiatorType='img' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize, count() as totalRequests by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize/totalRequests ",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  { "title": "Scripts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "CHR by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields event_details.env as env1\n|filter event_type='cdn_metrics' and (event_details.initiatorType='script') and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}] \n|stats COALESCE(count(event_details.sthcdncachemiss),0) as cachemiss,COALESCE(count(event_details.sthcdncachehit),0) as cachehit by bin(5m) as event_timestamp,env1\n|display event_timestamp,env1,cachehit/(cachehit+cachemiss)",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env1"
     ]
    }
   ]
  },
  {
   "title": "TTFB (p${percentile}): ${country}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields event_details.env as env\n|filter (event_details.initiatorType='script' or event_details.initiatorType='other') and env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.requestTime,${percentile}) as ttfb by env,bin(5m) as event_timestamp\n|display event_timestamp,env,ttfb",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Total bytes served by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.initiatorType='script' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Average Object Size by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.initiatorType='script' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize, count() as totalRequests by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize/totalRequests ",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and (event_details.initiatorType='script') and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats avg(event_details.compressRate) as compression by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  { "title": "CSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "CHR by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields event_details.env as env1\n|filter event_type='cdn_metrics' and (event_details.initiatorType='link') and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}] \n|stats COALESCE(count(event_details.sthcdncachemiss),0) as cachemiss,COALESCE(count(event_details.sthcdncachehit),0) as cachehit by bin(5m) as event_timestamp,env1\n|display event_timestamp,env1,cachehit/(cachehit+cachemiss)",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_timestamp",
      "env1"
     ]
    }
   ]
  },
  {
   "title": "TTFB (p${percentile}): ${country}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields event_details.env as env\n|filter event_details.initiatorType='link' and env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats pct(event_details.value,${percentile}) as ttfb by env,bin(5m) as event_timestamp\n|display event_timestamp,env,ttfb",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Total bytes served by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.initiatorType='link' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Average Object Size by environment : ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and event_details.initiatorType='link' and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats sum(event_details.transferSize) as transferSize, count() as totalRequests by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,transferSize/totalRequests ",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate by environment: ${country}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "filter event_type='cdn_metrics' and (event_details.initiatorType='link') and event_details.env in [${environment:singlequote}] and metadata.countryCode in [${country:singlequote}]\n|stats avg(event_details.compressRate) as compression by event_details.env,bin(5m) as event_timestamp\n|display event_timestamp,event_details.env,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_CloudFrontMonitoringStack-rum7f414c06"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.env",
      "event_timestamp"
     ]
    }
   ]
  }
 ]
}